// <auto-generated />
using ApiLabbVer2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLabbVer2.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiLabbVer2.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spela spel",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "äta mat",
                            Title = "mat"
                        },
                        new
                        {
                            Id = 3,
                            Description = "springa runt",
                            Title = "springa"
                        },
                        new
                        {
                            Id = 4,
                            Description = "bara älskar sova",
                            Title = "sova"
                        },
                        new
                        {
                            Id = 5,
                            Description = "flyga runt och sådant",
                            Title = "flyga"
                        },
                        new
                        {
                            Id = 6,
                            Description = "läsa böcker och sånt",
                            Title = "Läsa"
                        });
                });

            modelBuilder.Entity("ApiLabbVer2.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Interestid")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Link");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interestid = 1,
                            PersonId = 1,
                            Url = "https://www.aftonbladet.se/"
                        },
                        new
                        {
                            Id = 3,
                            Interestid = 3,
                            PersonId = 2,
                            Url = "https://www.youtube.com/"
                        },
                        new
                        {
                            Id = 5,
                            Interestid = 5,
                            PersonId = 3,
                            Url = "https://visitvarberg.se/uppleva/subbe-fyr"
                        },
                        new
                        {
                            Id = 6,
                            Interestid = 2,
                            PersonId = 4,
                            Url = "https://TotallyARealLink.Real"
                        },
                        new
                        {
                            Id = 8,
                            Interestid = 1,
                            PersonId = 5,
                            Url = "https://YEYEYEYEYE.com"
                        },
                        new
                        {
                            Id = 10,
                            Interestid = 4,
                            PersonId = 6,
                            Url = "https://halloDer"
                        });
                });

            modelBuilder.Entity("ApiLabbVer2.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peter",
                            PhoneNumber = 123456
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steve",
                            PhoneNumber = 223456
                        },
                        new
                        {
                            Id = 3,
                            Name = "David",
                            PhoneNumber = 323456
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rutger",
                            PhoneNumber = 423456
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stig",
                            PhoneNumber = 523456
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sten",
                            PhoneNumber = 623456
                        });
                });

            modelBuilder.Entity("ApiLabbVer2.Models.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Interestid")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interestid = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Interestid = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Interestid = 3,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            Interestid = 6,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            Interestid = 5,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            Interestid = 2,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 7,
                            Interestid = 3,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 8,
                            Interestid = 1,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 9,
                            Interestid = 4,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 10,
                            Interestid = 4,
                            PersonId = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
